### PR TITLE
Added Docker deployment/configuration

### PR DESCRIPTION
**Pull request by PhilipSchmid**
Hi there,

I needed Nanny to be able to run as Docker container. Therefore I dockerized this simple but awesome tool. It would be nice to see this improvement merged into the official Nanny repository.

Any feedback is welcome! Thanks.

Regards,
Philip

PS: It would also be nice to configure an official automated build job for this Docker image on the Docker Hub. @lunemec, can you set this up? This would allow people to simply run Nanny using a `docker run -d -v ${PWD}/nanny.toml:/nanny.toml -p 8080:8080 lunemec/nanny:0.3` command.

### CODE REVIEW

**Comment by lunemec** [comment]
@PhilipSchmid thanks for the PR! Once we finish this PR, I'll look into the automated docker builds.

**Comment by lunemec** [comment]
@PhilipSchmid I'll add versioning scripts to Nanny master, so you can use them in the docker builds.

**Comment by lunemec** [comment]
@PhilipSchmid I pushed it to current master, you can now use:
```bash
VERSION=$(cat VERSION)
```
to get nanny version for the dockerfile.

**Comment by PhilipSchmid** [comment]
@lunemec I just added the following VERSION support for the Docker image: https://github.com/lunemec/nanny/pull/14/commits/0b99ecb68771c494192de576b53d830f0217a450

Is that the way you mean? If not, can you please specify what you would like to achieve using the version from the `VERSION` file?

Thanks.

Regards,
Philip

**Comment by lunemec** [comment]
@PhilipSchmid yup, that is exactly what I meant. One file where the VERSION is, so all the tooling can just load it from there. It makes version increasing easier.

**Comment by PhilipSchmid** [comment]
@lunemec Alright, awesome. 

FYI: Inside the `docker-compose.yml` file the Nanny version is still fixed (`image: nanny:0.3`) but I currently see no nice way to set this version in a dynamic way.

Also inside die `Dockerfile` there is still a fixed URL `https://github.com/lunemec/nanny/archive/untagged-018d21470eb2f6c9ef3d.tar.gz` which downloads the Nanny version 0.3.  This is also kind of ugly. Would it might be possible to release Nanny releases under a "stable" URL like `https://github.com/lunemec/nanny/releases/download/$(cat VERSION)/nanny.tar.gz`?

Thanks.

Regards,
Philip

**Comment by PhilipSchmid** [comment]
@lunemec Well you are right. The ADD statement with the download of the `.tar.gz` isn't required anymore since I switched to building Nanny by myself inside the `Dockerfile`. It was previously needed because at the start of the "dockerization" process of Nanny, I just downloaded the Nanny binary but then I realised it does not run inside a `scratch` Docker image since it required dynamic libraries.

I now fixed the `Dockerfile` and the `docker-compose.yml` file.

Thanks.

Regards,
Philip

**Comment by lunemec** [comment]
@PhilipSchmid great! Thank you. Can you also go over the review comments I created? There are few more smaller things.

**Comment by PhilipSchmid** [comment]
@lunemec Which review comments? Sorry I can't see them.

Regards,
Philip

**Comment by lunemec** [comment]
https://github.com/lunemec/nanny/pull/14/files

**Comment by lunemec** [comment]
@PhilipSchmid sorry, I am used to gitlab workflow and github PRs don't make sense to me... Here are the requested changes. 😉

**Comment by lunemec** [comment]
@PhilipSchmid thank you, if you want, I can fix the rest - the user and exposed port...

**Comment by PhilipSchmid** [comment]
@lunemec I just added the `EXPOSE` definition to the `Dockerfile`. I also prepared a service user `nanny` to run the Nanny process. Unfortunately I can't get it to run when uncommenting `USER nanny`. If I do so, Nanny crashes with the following message:
```bash
service_1  | {"_t":"2018-08-13T19:55:25+0000", "_p":"1", "_l":"FTL", "_n":"~", "_m":"Unable to create/load sqlite storage", "dsn":"file:nanny.sqlite", "err":"unable to create sqlite table: unable to open database file", "_c":["nanny/cmd.runAPI() /go/src/nanny/cmd/root.go:140","nanny/cmd.run() /go/src/nanny/cmd/root.go:97","nanny/vendor/github.com/spf13/cobra.(*Command).execute() /go/src/nanny/vendor/github.com/spf13/cobra/command.go:766","nanny/vendor/github.com/spf13/cobra.(*Command).ExecuteC() /go/src/nanny/vendor/github.com/spf13/cobra/command.go:852","nanny/vendor/github.com/spf13/cobra.(*Command).Execute() /go/src/nanny/vendor/github.com/spf13/cobra/command.go:800","nanny/cmd.Execute() /go/src/nanny/cmd/root.go:242","main.main() /go/src/nanny/main.go:6","runtime.main() /usr/local/go/src/runtime/proc.go:198","runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:2361"]}
service_1  | panic: unable to create sqlite table: unable to open database file
service_1  | 
service_1  | goroutine 1 [running]:
service_1  | nanny/vendor/github.com/mgutz/logxi.(*DefaultLogger).Fatal(0xc420311b00, 0xb62537, 0x24, 0xc4202257c0, 0x4, 0x4)
service_1  | 	/go/src/nanny/vendor/github.com/mgutz/logxi/defaultLogger.go:133 +0xf4
service_1  | nanny/vendor/github.com/mgutz/logxi.Fatal(0xb62537, 0x24, 0xc4202257c0, 0x4, 0x4)
service_1  | 	/go/src/nanny/vendor/github.com/mgutz/logxi/methods.go:30 +0x67
service_1  | nanny/cmd.runAPI()
service_1  | 	/go/src/nanny/cmd/root.go:140 +0x24d
service_1  | nanny/cmd.run(0x10e9f40, 0x114c110, 0x0, 0x0)
service_1  | 	/go/src/nanny/cmd/root.go:97 +0x35
service_1  | nanny/vendor/github.com/spf13/cobra.(*Command).execute(0x10e9f40, 0xc42009a1b0, 0x0, 0x0, 0x10e9f40, 0xc42009a1b0)
service_1  | 	/go/src/nanny/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
service_1  | nanny/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x10e9f40, 0x1, 0x0, 0x10ea1a0)
service_1  | 	/go/src/nanny/vendor/github.com/spf13/cobra/command.go:852 +0x30a
service_1  | nanny/vendor/github.com/spf13/cobra.(*Command).Execute(0x10e9f40, 0xc42008a058, 0x0)
service_1  | 	/go/src/nanny/vendor/github.com/spf13/cobra/command.go:800 +0x2b
service_1  | nanny/cmd.Execute()
service_1  | 	/go/src/nanny/cmd/root.go:242 +0x2d
service_1  | main.main()
service_1  | 	/go/src/nanny/main.go:6 +0x20
nanny_service_1 exited with code 2
```
I mean.. the permission error make sense since the `nanny` user is not allowed to create the `/nanny.sqlite` file but how can you solve this in a nice way? Any guesses?

Thanks.

Regards,
Philip

**Comment by lunemec** [comment]
Nanny writes SQLite DB into a directory supplied in nanny.toml, so you need to have rights to write into it under the new user.

**Comment by PhilipSchmid** [comment]
Jup, thats clear to me. But how do you achieve this in a `scratch` Docker image (the current situation)? I see two possible solutions for this problem:

1. Switch to an image like `busybox`/`alpine` for the second build stage instead of using `scratch`. This way we could `chmod`/ `chown` the directory to the `nanny` user so Nanny is able to create and edit the SQLite file. This would also lead into a bit larger image but I guess that would still be acceptable.

2. Mounting a `nanny.sqlite` file via a bind mount inside the `docker-compose.yml` file to the same location where the Nanny binary is stored. This would require Nanny to be able to write the SQLite structure in an already existing empty file. Also then we would need to ensure the empty, external `nanny.sqlite` file (on the host system) must be owned by UID 1000 even though this could be a completely different user at host system level.

Do you see another possible solution for this permission problem? If not, which solution of the above two do you prefer? For me it's solution 1 because this way we could keep the requirements to files outside of our Docker as small as possible.

Thanks.

Regards,
Philip

**Comment by lunemec** [comment]
@PhilipSchmid I guess it didn't detect the configuration file properly, try running it with `LOGXI=*` to see what is happening.

**Comment by PhilipSchmid** [comment]
In which directory does the nanny binary search for the `nanny.toml`?

With debug enabled:
```bash
macbookpro:nanny phil$ docker-compose up
Recreating nanny_service_1 ... done
Attaching to nanny_service_1
service_1  | {"_t":"2018-08-14T07:42:50+0000", "_p":"1", "_l":"WRN", "_n":"~", "_m":"Config not found, using default stderr notifier."}
service_1  | {"_t":"2018-08-14T07:42:50+0000", "_p":"1", "_l":"INF", "_n":"~", "_m":"Nanny listening", "addr":""}
service_1  | {"_t":"2018-08-14T07:42:50+0000", "_p":"1", "_l":"FTL", "_n":"~", "_m":"Unable to start API server", "err":"listen tcp :80: bind: permission denied", "_c":["nanny/cmd.runAPI() /go/src/nanny/cmd/root.go:189","nanny/cmd.run() /go/src/nanny/cmd/root.go:97","nanny/vendor/github.com/spf13/cobra.(*Command).execute() /go/src/nanny/vendor/github.com/spf13/cobra/command.go:766","nanny/vendor/github.com/spf13/cobra.(*Command).ExecuteC() /go/src/nanny/vendor/github.com/spf13/cobra/command.go:852","nanny/vendor/github.com/spf13/cobra.(*Command).Execute() /go/src/nanny/vendor/github.com/spf13/cobra/command.go:800","nanny/cmd.Execute() /go/src/nanny/cmd/root.go:242","main.main() /go/src/nanny/main.go:6","runtime.main() /usr/local/go/src/runtime/proc.go:198","runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:2361"]}
service_1  | panic: listen tcp :80: bind: permission denied
service_1  | 
service_1  | goroutine 1 [running]:
service_1  | nanny/vendor/github.com/mgutz/logxi.(*DefaultLogger).Fatal(0xc4202ffac0, 0xb5ac7b, 0x1a, 0xc420498360, 0x2, 0x2)
service_1  | 	/go/src/nanny/vendor/github.com/mgutz/logxi/defaultLogger.go:133 +0xf4
service_1  | nanny/vendor/github.com/mgutz/logxi.Fatal(0xb5ac7b, 0x1a, 0xc420498360, 0x2, 0x2)
service_1  | 	/go/src/nanny/vendor/github.com/mgutz/logxi/methods.go:30 +0x67
service_1  | nanny/cmd.runAPI()
service_1  | 	/go/src/nanny/cmd/root.go:189 +0x68a
service_1  | nanny/cmd.run(0x10e9f40, 0x114c110, 0x0, 0x0)
service_1  | 	/go/src/nanny/cmd/root.go:97 +0x35
service_1  | nanny/vendor/github.com/spf13/cobra.(*Command).execute(0x10e9f40, 0xc42008e1b0, 0x0, 0x0, 0x10e9f40, 0xc42008e1b0)
service_1  | 	/go/src/nanny/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
service_1  | nanny/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x10e9f40, 0x1, 0x0, 0x10ea1a0)
service_1  | 	/go/src/nanny/vendor/github.com/spf13/cobra/command.go:852 +0x30a
service_1  | nanny/vendor/github.com/spf13/cobra.(*Command).Execute(0x10e9f40, 0xc420084058, 0x0)
service_1  | 	/go/src/nanny/vendor/github.com/spf13/cobra/command.go:800 +0x2b
service_1  | nanny/cmd.Execute()
service_1  | 	/go/src/nanny/cmd/root.go:242 +0x2d
service_1  | main.main()
service_1  | 	/go/src/nanny/main.go:6 +0x20
nanny_service_1 exited with code 2
```

If I add the command `ls -la /opt` inside the `docker-compose.yml` file, I see the `nanny.toml` and also with the correct permissions:
```bash
macbookpro:nanny phil$ docker-compose up
Recreating nanny_service_1 ... done
Attaching to nanny_service_1
service_1  | total 16424
service_1  | drwxr-xr-x    1 nanny    nanny         4096 Aug 14 07:43 .
service_1  | drwxr-xr-x    1 root     root          4096 Aug 14 07:43 ..
service_1  | -rwxr-xr-x    1 nanny    nanny     16802480 Aug 14 06:57 nanny
service_1  | -rw-r--r--    1 nanny    nanny          572 Aug 14 07:18 nanny.toml
nanny_service_1 exited with code 0
```

Thanks.

Regards,
Philip

**Comment by lunemec** [comment]
Currently it is only searching in the working directory: https://github.com/lunemec/nanny/blob/master/cmd/root.go#L266

Or you can pass `--config` with location.

**Comment by PhilipSchmid** [comment]
Well the working directory for the Docker is `WORKDIR /opt` and the `nanny.toml` is bind mounted to `/opt` (`${PWD}/nanny.toml:/opt/nanny.toml`). `/opt/nanny --config nanny.toml` does not work while `/opt/nanny --config /opt/nanny.toml` does (but this still gives me the SQLite exception). To me it seems like it's only looking inside the `/` for a Nanny configuration.

```bash
macbookpro:nanny phil$ docker-compose up
Recreating nanny_service_1 ... done
Attaching to nanny_service_1
service_1  | {"_t":"2018-08-14T07:52:20+0000", "_p":"1", "_l":"INF", "_n":"~", "_m":"Using config file", "path":"/opt/nanny.toml"}
service_1  | {"_t":"2018-08-14T07:52:20+0000", "_p":"1", "_l":"FTL", "_n":"~", "_m":"Unable to create/load sqlite storage", "dsn":"file:nanny.sqlite", "err":"unable to create sqlite table: unable to open database file", "_c":["nanny/cmd.runAPI() /go/src/nanny/cmd/root.go:140","nanny/cmd.run() /go/src/nanny/cmd/root.go:97","nanny/vendor/github.com/spf13/cobra.(*Command).execute() /go/src/nanny/vendor/github.com/spf13/cobra/command.go:766","nanny/vendor/github.com/spf13/cobra.(*Command).ExecuteC() /go/src/nanny/vendor/github.com/spf13/cobra/command.go:852","nanny/vendor/github.com/spf13/cobra.(*Command).Execute() /go/src/nanny/vendor/github.com/spf13/cobra/command.go:800","nanny/cmd.Execute() /go/src/nanny/cmd/root.go:242","main.main() /go/src/nanny/main.go:6","runtime.main() /usr/local/go/src/runtime/proc.go:198","runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:2361"]}
service_1  | panic: unable to create sqlite table: unable to open database file
service_1  | 
service_1  | goroutine 1 [running]:
service_1  | nanny/vendor/github.com/mgutz/logxi.(*DefaultLogger).Fatal(0xc420301ac0, 0xb62537, 0x24, 0xc420213800, 0x4, 0x4)
service_1  | 	/go/src/nanny/vendor/github.com/mgutz/logxi/defaultLogger.go:133 +0xf4
service_1  | nanny/vendor/github.com/mgutz/logxi.Fatal(0xb62537, 0x24, 0xc420213800, 0x4, 0x4)
service_1  | 	/go/src/nanny/vendor/github.com/mgutz/logxi/methods.go:30 +0x67
service_1  | nanny/cmd.runAPI()
service_1  | 	/go/src/nanny/cmd/root.go:140 +0x24d
service_1  | nanny/cmd.run(0x10e9f40, 0xc4203fa160, 0x0, 0x2)
service_1  | 	/go/src/nanny/cmd/root.go:97 +0x35
service_1  | nanny/vendor/github.com/spf13/cobra.(*Command).execute(0x10e9f40, 0xc420092160, 0x2, 0x2, 0x10e9f40, 0xc420092160)
service_1  | 	/go/src/nanny/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
service_1  | nanny/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x10e9f40, 0x1, 0x0, 0x10ea1a0)
service_1  | 	/go/src/nanny/vendor/github.com/spf13/cobra/command.go:852 +0x30a
service_1  | nanny/vendor/github.com/spf13/cobra.(*Command).Execute(0x10e9f40, 0xc420086058, 0x0)
service_1  | 	/go/src/nanny/vendor/github.com/spf13/cobra/command.go:800 +0x2b
service_1  | nanny/cmd.Execute()
service_1  | 	/go/src/nanny/cmd/root.go:242 +0x2d
service_1  | main.main()
service_1  | 	/go/src/nanny/main.go:6 +0x20
nanny_service_1 exited with code 2
```

Regards,
Philip

**Comment by lunemec** [comment]
Can you push these changes to your branch? I'll try it.

**Comment by lunemec** [comment]
I just ran this:
```bash
 λ docker run -it --rm=true -e LOGXI="*" -v `pwd`/nanny.toml:/opt/nanny.toml nanny:latest
08:27:04.828016 INF ~ Using config file path: /opt/nanny.toml
08:27:04.839313 INF ~ Nanny listening addr: 0.0.0.0:8080
^C08:27:05.597089 INF ~ Nanny shutting down.
```
and it works fine, maybe the compose is running something different?

**Comment by PhilipSchmid** [comment]
Hmm you are right. It works in my setup too when I run it using `docker run`:
```bash
macbookpro:nanny phil$ docker run -it --rm -e LOGXI="*" -v `pwd`/nanny.toml:/opt/nanny.toml -p 8080:8080 -e NANNY_ADDR=0.0.0.0:8080 nanny:latest
08:35:04.631237 INF ~ Using config file path: /opt/nanny.toml
08:35:04.643262 INF ~ Nanny listening addr: 0.0.0.0:8080
2018-08-14T08:35:26Z: Nanny: I did not hear from "my awesome program@172.17.0.1" in 5s! (Meta: map[])
```

Now it also works with the `docker-compose.yml` file..:
```bash
macbookpro:nanny phil$ docker-compose up
Starting nanny_service_1 ... done
Attaching to nanny_service_1
service_1  | {"_t":"2018-08-14T08:42:41+0000", "_p":"1", "_l":"INF", "_n":"~", "_m":"Using config file", "path":"/opt/nanny.toml"}
service_1  | {"_t":"2018-08-14T08:42:41+0000", "_p":"1", "_l":"INF", "_n":"~", "_m":"Nanny listening", "addr":"0.0.0.0:8080"}
^CGracefully stopping... (press Ctrl+C again to force)
```

To be honest, I don't know why it's working now 😅. Perhaps because of a caching issue? Nevertheless, I now also updated the `README.md`. Could you please review these changes? I guess then is no open TODO left. Am I right?

Thanks.

Regards,
Philip

**Comment by lunemec** [comment]
Cool, thanks for doing this!

**Comment by lunemec** [comment]
@PhilipSchmid https://hub.docker.com/r/lunemec/nanny/

**Comment by PhilipSchmid** [comment]
@lunemec Thanks for the official Docker image. How about setting up an Automated Build on the Docker Hub instead of a manual one like right now and configure 2 build jobs? 1 build job for the `latest` tag and 1 for the specific version tag (e.g. `0.4.0`).

Perhaps it would also be helpful to write inside the `README.md` that there is an official image (incl. URL).

Regards,
Philip

**Comment by lunemec** [comment]
Well, I linked the github repo to the docker hub, so I was hoping it was already automated.
What would be the difference between the build jobs? Only the tag?

**Comment by PhilipSchmid** [comment]
One trigger could just track the `master` branch (the `latest` build job) and the other build job could watch for specific versions via git tags and if you then add a git tag for a specific version - let's says you release nanny version 0.5.0 - a Docker image with the tag `lunemec/nanny:0.5.0` would automatically be built - beside `lunemec/nanny:latest`.

Regards,
Philip

**Comment by lunemec** [comment]
@PhilipSchmid what is your docker hub username? I'll add you as collaborator. I think I have the tag autobuild set-up, but for some reason can't trigger it.

**Comment by PhilipSchmid** [comment]
It's `pschmid`.

**Pull request merged**
